name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, master]
    types: 
      - opened 
      - synchronize 

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run playWright test
        run: npx playwright install --with-deps && npm run test:e2e
    
  notify-build:
    needs: build_and_test
    runs-on: ubuntu-20.04
    steps:
      - name: Build Success
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: warn
          details: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: build_and_test
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: 'Change ownership build file'
        run: chmod -v +x build.sh
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.REDNER_API_KEY }}
          # wait-for-success: true
  
  notify-deploy:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Deployment Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: Deplyoment successful
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

